name: Say "Hello World" every 5 minutes. 3

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes

jobs:
  say-hello:
    name: Test say-hello
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: |
          echo "Hello, world!"

# -30- #
