name: Say "Hello World" every 5 minutes. 5

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes

jobs:
  say-hello:
    name: Test say-hello
    runs-on: Ubuntu-20.04
    steps:
      - name: Hello World
        run: |
          echo "Hello World! $(date -Imin)"

# -30- #
